# Generated by Django 3.1.5 on 2021-01-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_id', models.IntegerField(verbose_name='peer id')),
                ('have_access', models.BooleanField(default=False, verbose_name='Есть доступ к БД')),
            ],
            options={
                'verbose_name': 'Пользователи',
            },
        ),
    ]
