# Generated by Django 3.1.5 on 2021-01-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('text', models.TextField(verbose_name='Текст анкеты')),
                ('city', models.TextField(verbose_name='Город')),
                ('profile_url', models.TextField(verbose_name='Ссылка')),
                ('photo_url', models.TextField(verbose_name='Ссылка на фото')),
            ],
            options={
                'verbose_name': 'Анкета',
            },
        ),
    ]
