# Generated by Django 3.1.5 on 2021-01-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='age',
            field=models.TextField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='city',
            field=models.TextField(blank=True, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='photo_url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='profile_url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст анкеты'),
        ),
    ]
