# Generated by Django 3.1.5 on 2021-01-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20210117_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_input_profile_url',
            field=models.BooleanField(blank=True, null=True, verbose_name='Вводит ссылку на профиль'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_url_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.questionnaire'),
        ),
    ]
