# Generated by Django 3.1.5 on 2021-01-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20210117_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_added',
            field=models.IntegerField(default=0, verbose_name='Количество добавленных анкет'),
        ),
    ]
